### ISSUE TITLE
vue create --preset throws error

### ISSUE THREAD

**Issue by turbopasi** [turbopasi/vue-cli-plugin-vuesr#16]
When using the `--preset` flag as in `vue create --preset turbopasi/vue-cli-plugin-vuesr` it produces the following error

```
Preset options:
 ERROR  Error: You must provide a `name` parameter
Error: You must provide a `name` parameter
    at InputPrompt.throwParamError (C:\Users\Pascal\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\inquirer\lib\prompts\base.js:73:11)
    at new Prompt (C:\Users\Pascal\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\inquirer\lib\prompts\base.js:33:12)
    at new InputPrompt (C:\Users\Pascal\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\inquirer\lib\prompts\input.js:11:1)    at PromptUI.fetchAnswer (C:\Users\Pascal\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\inquirer\lib\ui\prompt.js:85:25)
    at MergeMapSubscriber._tryNext (C:\Users\Pascal\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (C:\Users\Pascal\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\Pascal\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\rxjs\internal\Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (C:\Users\Pascal\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (C:\Users\Pascal\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (C:\Users\Pascal\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\rxjs\internal\Subscriber.js:66:18)
```

**Comment by turbopasi** [comment]
Fixed 99d69ee298aba2f85de943d85421064ef17235bf & fa41598525fefe79535b13865b325801e913e648
